trigger:
- master

resources:
- repo: self

stages:
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'AdminTurnedDevOpsSkylinesAcademyCode-1867.default'
    strategy:
      runOnce:
        deploy:
          steps:             
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/KubernetesManifest/nginx.yml
