trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'b7cf2898-2d12-4582-816f-3d5be95fd981'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  

stages:
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'AdminTurnedDevOpsSkylinesAcademyCode-1867.default'
    strategy:
      runOnce:
        deploy:
          steps:             
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/KubernetesManifest/nginx.yml
