trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
- repo: self

stages:
- stage: Deploy
  displayName: Deploy stage

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'AdminTurnedDevOpsSkylinesAcademyCode-1867.default'
    strategy:
      runOnce:
        deploy:
          steps:             
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                KubernetesManifest/nginx.yml
