apiVersion: v1
kind: Service
metadata:
    name: adminturneddevopsskylinesacademycode
spec:
    type: LoadBalancer
    ports:
    - port: 808 
    selector:
        app: adminturneddevopsskylinesacademycode