apiVersion: v1
kind: Service
metadata:
  name: gowebapi
  labels:
    app: gowebapi
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: gowebapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowebapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gowebapi
  template:
    metadata:
      labels:
        app: gowebapi
    spec:
      containers:
      - name: gowebapi
        image: skylinesacr92.azurecr.io/go/webapi:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080